# Generated by Django 2.0.2 on 2018-09-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.CharField(blank=True, max_length=255)),
                ('contents', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('voting_status', models.IntegerField(default=0)),
                ('answer', models.TextField(blank=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('vote2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('response', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.VoteQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
