# Generated by Django 2.0.2 on 2018-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votequestion',
            name='is_active',
        ),
        migrations.AddField(
            model_name='votequestion',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
