# Generated by Django 2.0.7 on 2019-09-27 12:12

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_TF',
            field=models.BooleanField(default=False, verbose_name=courses.models.Lecture),
        ),
        migrations.AlterField(
            model_name='response',
            name='vote1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='vote2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
