# Generated by Django 2.0.2 on 2018-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20180915_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresponse',
            name='vote1',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AlterField(
            model_name='voteresponse',
            name='vote2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
