# Generated by Django 2.0.7 on 2019-09-27 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20190927_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='v_response',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
