# Generated by Django 2.0.2 on 2018-09-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20180915_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votequestion',
            old_name='voting_status',
            new_name='is_active',
        ),
    ]
