# Generated by Django 2.0.2 on 2018-09-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('votes', '0005_auto_20180916_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteResponse',
            new_name='Response',
        ),
    ]
