# Generated by Django 2.0.2 on 2018-09-21 04:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('courses', '0002_remove_lecture_title'),
        ('votes', '0006_auto_20180921_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteQuestion',
            new_name='Question',
        ),
    ]
