# Generated by Django 2.0.2 on 2018-09-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_delete_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contents',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
