# Generated by Django 2.0.2 on 2018-09-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20180928_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='contents',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
