# Generated by Django 2.0.2 on 2018-10-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180926_2209'),
        ('votes', '0012_response_contents'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'student')},
        ),
    ]
