# Generated by Django 2.0.7 on 2019-08-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_score', models.IntegerField(null=True)),
                ('final_score', models.IntegerField(null=True)),
                ('attendance_score', models.IntegerField(null=True)),
                ('total_web_work_score', models.IntegerField(null=True)),
                ('total_pre_class_score', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grade.student+', to='accounts.Student', unique=True)),
            ],
        ),
    ]
