# Generated by Django 2.0.7 on 2019-09-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceinstance',
            old_name='create_date',
            new_name='datestamp',
        ),
    ]
