# Generated by Django 2.2.4 on 2019-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='attendance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='middle_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_pre_class_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_web_work_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
