# Generated by Django 2.0.7 on 2019-09-01 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20190901_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinstance',
            name='datestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
