# Generated by Django 2.0.7 on 2019-09-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_auto_20190901_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinstance',
            name='datestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
