# Generated by Django 2.0.7 on 2020-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
