# Generated by Django 2.2.8 on 2020-01-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200128_1155'),
        ('accounts', '0001_initial'),
        ('onlineclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AddField(
            model_name='video',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lecture'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VideoTraker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_vote_submit', models.BooleanField(default=False)),
                ('second_vote_submit', models.BooleanField(default=False)),
                ('discussion_submit', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('Video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineclasses.Video')),
            ],
            options={
                'unique_together': {('Student', 'Video')},
            },
        ),
    ]
