# Generated by Django 2.0.7 on 2020-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_explanation',
            field=models.BooleanField(default=False),
        ),
    ]
