# Generated by Django 2.2.8 on 2020-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('onlineclasses', '0002_auto_20200129_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoTraker',
            new_name='VideoTracker',
        ),
    ]
