# Generated by Django 2.2.8 on 2020-02-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclasses', '0002_video_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='sequence',
            new_name='index',
        ),
    ]
