# Generated by Django 2.2.8 on 2020-01-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
        ('onlineclasses', '0004_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Question'),
        ),
    ]
