# Generated by Django 2.2.8 on 2020-02-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('onlineclasses', '0005_video_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotracker',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='videotracker',
            old_name='Video',
            new_name='video',
        ),
        migrations.AlterUniqueTogether(
            name='videotracker',
            unique_together={('student', 'video')},
        ),
    ]
