# Generated by Django 2.2.8 on 2020-02-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200128_1155'),
        ('onlineclasses', '0006_auto_20200203_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Group')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineclasses.Video')),
            ],
        ),
    ]
