# Generated by Django 2.0.7 on 2020-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tmp_no',
            field=models.IntegerField(default=0),
        ),
    ]
