# Generated by Django 2.0.2 on 2018-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
    ]
