# Generated by Django 2.0.7 on 2020-04-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_group_tmp_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tmp_no',
        ),
    ]
