# Generated by Django 2.0.7 on 2020-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_group_tmp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tmp_no',
            field=models.IntegerField(default=0),
        ),
    ]
