# Generated by Django 2.2.4 on 2019-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='Course',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('title', 'course')},
        ),
    ]
