# Generated by Django 2.2.4 on 2019-10-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('homework', '0002_auto_20191012_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworktraker',
            old_name='Homework',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='homeworktraker',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='homeworktraker',
            unique_together={('student', 'homework')},
        ),
    ]
