# Generated by Django 2.2.4 on 2019-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20190826_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
