# Generated by Django 2.0.7 on 2019-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190827_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='optional_readings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
