# Generated by Django 2.2.4 on 2019-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('homework', '0003_auto_20191012_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeworkTraker',
            new_name='HomeworkTracker',
        ),
    ]
