# Generated by Django 2.1.1 on 2019-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_optional_readings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='quetions_image',
        ),
        migrations.AddField(
            model_name='homework',
            name='questions',
            field=models.TextField(blank=True),
        ),
    ]
